/*
Otito Ingester documentation

A suite of APIs to store and manage request and response logs

API version: 0.0.1
Contact: lanre@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerAPIError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerAPIError{}

// ServerAPIError struct for ServerAPIError
type ServerAPIError struct {
	// Generic message that tells you the status of the operation
	Message *string `json:"message,omitempty"`
	Status *bool `json:"status,omitempty"`
}

// NewServerAPIError instantiates a new ServerAPIError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerAPIError() *ServerAPIError {
	this := ServerAPIError{}
	return &this
}

// NewServerAPIErrorWithDefaults instantiates a new ServerAPIError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerAPIErrorWithDefaults() *ServerAPIError {
	this := ServerAPIError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerAPIError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAPIError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerAPIError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerAPIError) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServerAPIError) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAPIError) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServerAPIError) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ServerAPIError) SetStatus(v bool) {
	o.Status = &v
}

func (o ServerAPIError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerAPIError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableServerAPIError struct {
	value *ServerAPIError
	isSet bool
}

func (v NullableServerAPIError) Get() *ServerAPIError {
	return v.value
}

func (v *NullableServerAPIError) Set(val *ServerAPIError) {
	v.value = val
	v.isSet = true
}

func (v NullableServerAPIError) IsSet() bool {
	return v.isSet
}

func (v *NullableServerAPIError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerAPIError(val *ServerAPIError) *NullableServerAPIError {
	return &NullableServerAPIError{value: val, isSet: true}
}

func (v NullableServerAPIError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerAPIError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


