/*
Otito Ingester documentation

A suite of APIs to store and manage request and response logs

API version: 0.0.1
Contact: lanre@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerMessageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerMessageRequest{}

// ServerMessageRequest struct for ServerMessageRequest
type ServerMessageRequest struct {
	Messages []ServerMessageRequestMessagesInner `json:"messages,omitempty"`
}

// NewServerMessageRequest instantiates a new ServerMessageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerMessageRequest() *ServerMessageRequest {
	this := ServerMessageRequest{}
	return &this
}

// NewServerMessageRequestWithDefaults instantiates a new ServerMessageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerMessageRequestWithDefaults() *ServerMessageRequest {
	this := ServerMessageRequest{}
	return &this
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *ServerMessageRequest) GetMessages() []ServerMessageRequestMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []ServerMessageRequestMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerMessageRequest) GetMessagesOk() ([]ServerMessageRequestMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *ServerMessageRequest) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []ServerMessageRequestMessagesInner and assigns it to the Messages field.
func (o *ServerMessageRequest) SetMessages(v []ServerMessageRequestMessagesInner) {
	o.Messages = v
}

func (o ServerMessageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerMessageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableServerMessageRequest struct {
	value *ServerMessageRequest
	isSet bool
}

func (v NullableServerMessageRequest) Get() *ServerMessageRequest {
	return v.value
}

func (v *NullableServerMessageRequest) Set(val *ServerMessageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServerMessageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServerMessageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerMessageRequest(val *ServerMessageRequest) *NullableServerMessageRequest {
	return &NullableServerMessageRequest{value: val, isSet: true}
}

func (v NullableServerMessageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerMessageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


