/*
Otito API documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: contact@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerAPIStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerAPIStatus{}

// ServerAPIStatus struct for ServerAPIStatus
type ServerAPIStatus struct {
	// Generic message that tells you the status of the operation
	Message *string `json:"message,omitempty"`
	Status *bool `json:"status,omitempty"`
}

// NewServerAPIStatus instantiates a new ServerAPIStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerAPIStatus() *ServerAPIStatus {
	this := ServerAPIStatus{}
	return &this
}

// NewServerAPIStatusWithDefaults instantiates a new ServerAPIStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerAPIStatusWithDefaults() *ServerAPIStatus {
	this := ServerAPIStatus{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerAPIStatus) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAPIStatus) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerAPIStatus) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerAPIStatus) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServerAPIStatus) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerAPIStatus) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServerAPIStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ServerAPIStatus) SetStatus(v bool) {
	o.Status = &v
}

func (o ServerAPIStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerAPIStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableServerAPIStatus struct {
	value *ServerAPIStatus
	isSet bool
}

func (v NullableServerAPIStatus) Get() *ServerAPIStatus {
	return v.value
}

func (v *NullableServerAPIStatus) Set(val *ServerAPIStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableServerAPIStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableServerAPIStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerAPIStatus(val *ServerAPIStatus) *NullableServerAPIStatus {
	return &NullableServerAPIStatus{value: val, isSet: true}
}

func (v NullableServerAPIStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerAPIStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


