/*
Otito API documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: contact@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerUrlResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerUrlResp{}

// ServerUrlResp struct for ServerUrlResp
type ServerUrlResp struct {
	// Generic message that tells you the status of the operation
	Message *string `json:"message,omitempty"`
	Status *bool `json:"status,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewServerUrlResp instantiates a new ServerUrlResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerUrlResp() *ServerUrlResp {
	this := ServerUrlResp{}
	return &this
}

// NewServerUrlRespWithDefaults instantiates a new ServerUrlResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerUrlRespWithDefaults() *ServerUrlResp {
	this := ServerUrlResp{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ServerUrlResp) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerUrlResp) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ServerUrlResp) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ServerUrlResp) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServerUrlResp) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerUrlResp) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServerUrlResp) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *ServerUrlResp) SetStatus(v bool) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ServerUrlResp) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerUrlResp) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ServerUrlResp) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ServerUrlResp) SetUrl(v string) {
	o.Url = &v
}

func (o ServerUrlResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerUrlResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableServerUrlResp struct {
	value *ServerUrlResp
	isSet bool
}

func (v NullableServerUrlResp) Get() *ServerUrlResp {
	return v.value
}

func (v *NullableServerUrlResp) Set(val *ServerUrlResp) {
	v.value = val
	v.isSet = true
}

func (v NullableServerUrlResp) IsSet() bool {
	return v.isSet
}

func (v *NullableServerUrlResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerUrlResp(val *ServerUrlResp) *NullableServerUrlResp {
	return &NullableServerUrlResp{value: val, isSet: true}
}

func (v NullableServerUrlResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerUrlResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


