/*
Otito API documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: contact@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerSwaggerMessageRespMessagesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerSwaggerMessageRespMessagesInner{}

// ServerSwaggerMessageRespMessagesInner struct for ServerSwaggerMessageRespMessagesInner
type ServerSwaggerMessageRespMessagesInner struct {
	ApplicationId *string `json:"application_id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	// This is for the request
	IpAddress *string `json:"ip_address,omitempty"`
	Method *string `json:"method,omitempty"`
	OrganisationId *string `json:"organisation_id,omitempty"`
	Path *string `json:"path,omitempty"`
	Reference *string `json:"reference,omitempty"`
	Request *ServerMessageHTTPDefinition `json:"request,omitempty"`
	Response *ServerMessageHTTPDefinition `json:"response,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// NewServerSwaggerMessageRespMessagesInner instantiates a new ServerSwaggerMessageRespMessagesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerSwaggerMessageRespMessagesInner() *ServerSwaggerMessageRespMessagesInner {
	this := ServerSwaggerMessageRespMessagesInner{}
	return &this
}

// NewServerSwaggerMessageRespMessagesInnerWithDefaults instantiates a new ServerSwaggerMessageRespMessagesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerSwaggerMessageRespMessagesInnerWithDefaults() *ServerSwaggerMessageRespMessagesInner {
	this := ServerSwaggerMessageRespMessagesInner{}
	return &this
}

// GetApplicationId returns the ApplicationId field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetApplicationId() string {
	if o == nil || IsNil(o.ApplicationId) {
		var ret string
		return ret
	}
	return *o.ApplicationId
}

// GetApplicationIdOk returns a tuple with the ApplicationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetApplicationIdOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationId) {
		return nil, false
	}
	return o.ApplicationId, true
}

// HasApplicationId returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasApplicationId() bool {
	if o != nil && !IsNil(o.ApplicationId) {
		return true
	}

	return false
}

// SetApplicationId gets a reference to the given string and assigns it to the ApplicationId field.
func (o *ServerSwaggerMessageRespMessagesInner) SetApplicationId(v string) {
	o.ApplicationId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ServerSwaggerMessageRespMessagesInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServerSwaggerMessageRespMessagesInner) SetId(v string) {
	o.Id = &v
}

// GetIpAddress returns the IpAddress field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetIpAddress() string {
	if o == nil || IsNil(o.IpAddress) {
		var ret string
		return ret
	}
	return *o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetIpAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IpAddress) {
		return nil, false
	}
	return o.IpAddress, true
}

// HasIpAddress returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasIpAddress() bool {
	if o != nil && !IsNil(o.IpAddress) {
		return true
	}

	return false
}

// SetIpAddress gets a reference to the given string and assigns it to the IpAddress field.
func (o *ServerSwaggerMessageRespMessagesInner) SetIpAddress(v string) {
	o.IpAddress = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *ServerSwaggerMessageRespMessagesInner) SetMethod(v string) {
	o.Method = &v
}

// GetOrganisationId returns the OrganisationId field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetOrganisationId() string {
	if o == nil || IsNil(o.OrganisationId) {
		var ret string
		return ret
	}
	return *o.OrganisationId
}

// GetOrganisationIdOk returns a tuple with the OrganisationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetOrganisationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganisationId) {
		return nil, false
	}
	return o.OrganisationId, true
}

// HasOrganisationId returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasOrganisationId() bool {
	if o != nil && !IsNil(o.OrganisationId) {
		return true
	}

	return false
}

// SetOrganisationId gets a reference to the given string and assigns it to the OrganisationId field.
func (o *ServerSwaggerMessageRespMessagesInner) SetOrganisationId(v string) {
	o.OrganisationId = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ServerSwaggerMessageRespMessagesInner) SetPath(v string) {
	o.Path = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *ServerSwaggerMessageRespMessagesInner) SetReference(v string) {
	o.Reference = &v
}

// GetRequest returns the Request field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetRequest() ServerMessageHTTPDefinition {
	if o == nil || IsNil(o.Request) {
		var ret ServerMessageHTTPDefinition
		return ret
	}
	return *o.Request
}

// GetRequestOk returns a tuple with the Request field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetRequestOk() (*ServerMessageHTTPDefinition, bool) {
	if o == nil || IsNil(o.Request) {
		return nil, false
	}
	return o.Request, true
}

// HasRequest returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasRequest() bool {
	if o != nil && !IsNil(o.Request) {
		return true
	}

	return false
}

// SetRequest gets a reference to the given ServerMessageHTTPDefinition and assigns it to the Request field.
func (o *ServerSwaggerMessageRespMessagesInner) SetRequest(v ServerMessageHTTPDefinition) {
	o.Request = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetResponse() ServerMessageHTTPDefinition {
	if o == nil || IsNil(o.Response) {
		var ret ServerMessageHTTPDefinition
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetResponseOk() (*ServerMessageHTTPDefinition, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given ServerMessageHTTPDefinition and assigns it to the Response field.
func (o *ServerSwaggerMessageRespMessagesInner) SetResponse(v ServerMessageHTTPDefinition) {
	o.Response = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ServerSwaggerMessageRespMessagesInner) SetStatusCode(v int32) {
	o.StatusCode = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ServerSwaggerMessageRespMessagesInner) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageRespMessagesInner) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ServerSwaggerMessageRespMessagesInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ServerSwaggerMessageRespMessagesInner) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o ServerSwaggerMessageRespMessagesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerSwaggerMessageRespMessagesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationId) {
		toSerialize["application_id"] = o.ApplicationId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IpAddress) {
		toSerialize["ip_address"] = o.IpAddress
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.OrganisationId) {
		toSerialize["organisation_id"] = o.OrganisationId
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Request) {
		toSerialize["request"] = o.Request
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableServerSwaggerMessageRespMessagesInner struct {
	value *ServerSwaggerMessageRespMessagesInner
	isSet bool
}

func (v NullableServerSwaggerMessageRespMessagesInner) Get() *ServerSwaggerMessageRespMessagesInner {
	return v.value
}

func (v *NullableServerSwaggerMessageRespMessagesInner) Set(val *ServerSwaggerMessageRespMessagesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServerSwaggerMessageRespMessagesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServerSwaggerMessageRespMessagesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerSwaggerMessageRespMessagesInner(val *ServerSwaggerMessageRespMessagesInner) *NullableServerSwaggerMessageRespMessagesInner {
	return &NullableServerSwaggerMessageRespMessagesInner{value: val, isSet: true}
}

func (v NullableServerSwaggerMessageRespMessagesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerSwaggerMessageRespMessagesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


