/*
Otito API documentation

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
Contact: contact@ayinke.ventures
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerSwaggerMessageResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerSwaggerMessageResp{}

// ServerSwaggerMessageResp struct for ServerSwaggerMessageResp
type ServerSwaggerMessageResp struct {
	Messages []ServerSwaggerMessageRespMessagesInner `json:"messages,omitempty"`
}

// NewServerSwaggerMessageResp instantiates a new ServerSwaggerMessageResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerSwaggerMessageResp() *ServerSwaggerMessageResp {
	this := ServerSwaggerMessageResp{}
	return &this
}

// NewServerSwaggerMessageRespWithDefaults instantiates a new ServerSwaggerMessageResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerSwaggerMessageRespWithDefaults() *ServerSwaggerMessageResp {
	this := ServerSwaggerMessageResp{}
	return &this
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *ServerSwaggerMessageResp) GetMessages() []ServerSwaggerMessageRespMessagesInner {
	if o == nil || IsNil(o.Messages) {
		var ret []ServerSwaggerMessageRespMessagesInner
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerSwaggerMessageResp) GetMessagesOk() ([]ServerSwaggerMessageRespMessagesInner, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *ServerSwaggerMessageResp) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []ServerSwaggerMessageRespMessagesInner and assigns it to the Messages field.
func (o *ServerSwaggerMessageResp) SetMessages(v []ServerSwaggerMessageRespMessagesInner) {
	o.Messages = v
}

func (o ServerSwaggerMessageResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerSwaggerMessageResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	return toSerialize, nil
}

type NullableServerSwaggerMessageResp struct {
	value *ServerSwaggerMessageResp
	isSet bool
}

func (v NullableServerSwaggerMessageResp) Get() *ServerSwaggerMessageResp {
	return v.value
}

func (v *NullableServerSwaggerMessageResp) Set(val *ServerSwaggerMessageResp) {
	v.value = val
	v.isSet = true
}

func (v NullableServerSwaggerMessageResp) IsSet() bool {
	return v.isSet
}

func (v *NullableServerSwaggerMessageResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerSwaggerMessageResp(val *ServerSwaggerMessageResp) *NullableServerSwaggerMessageResp {
	return &NullableServerSwaggerMessageResp{value: val, isSet: true}
}

func (v NullableServerSwaggerMessageResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerSwaggerMessageResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


